# 项目相关配置
bing-lkcnads:
  # 名称
  name: Bing
  # 版本
  version: 0.1.0.SNAPSHOT
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 环境
  environment: ${profile.active}
  #服务器的ip与端口
  server-ip-port: localhost:${springboot.server.port}

# jwt 配置
jwt:
  # 加密密钥
  secret: Bing-fish-Alpha-9961
  # token有效时长(分钟)
  expire: 60
  # header 名称
  header: token
# 日志设置
logging:
  level:
    # 日志等级设置
    root: info
  file:
    # 日志保存目录与日志名
    name: ${springboot.path.log}/spring.log

server:
  # 端口号设置
  port: ${springboot.server.port}
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# mybatis相关的一些叭
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mappers/*.xml

# 反向代理
proxy:
  # 代理内容
  nginx-static-resource:
    url: /static_resource/*
    target_url: http://${springboot.server.ip}:28080/static/
    name: 静态资源

# spring配置(非常非常非常重要)
spring:

#  cloud:
#    nacos:
#      server-addr: ${springboot.server.ip}:8848
  # rabbitmq相关的配置
  rabbitmq:
    host: ${springboot.server.ip}
    port: 5672
    username: Bing
    password: bkhra571
    # 虚拟主机
    virtual-host: msg
    listener:
      simple:
        #n秒内取得多条消息
        prefetch: 1
  #热部署
  devtools:
    restart:
      poll-interval: 1s
  # 页面缓存
  thymeleaf:
    cache: ${springboot.server.page.cache}
  freemarker:
    cache: ${springboot.server.page.cache}
  groovy:
    template:
      cache: ${springboot.server.page.cache}
  servlet:
    context-path: /
    multipart:
      # 单个文件最大上传
      max-file-size: 30MB
      # 多个文件最大上传
      max-request-size: 100MB
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  messages:
    basename: msg/messages
    encoding: UTF-8
  redis:
    # 地址
    host: ${springboot.server.ip}
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: bkhra571
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池的最大数据库连接数
        max-active: 30
        # 连接池最大阻塞等待时间（使用负值[-1]表示没有限制）
        max-wait: 30000ms
  datasource:
    # 数据库连接池与jdbc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 主库数据源
    url: jdbc:mysql://${springboot.server.ip}:24406/sqluser?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: Bing
    password: bkhra571
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: Bing
        login-password: bkhra571
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# 应用监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:

  info:
    env:
      enabled: true
info:
  app:
    name: 还没想好
    version: 0.1.0.SNAPSHOT
    qq: 3035936740
    email:
      - ep3035936740@126.com
      - BingEp3307@gmail.com
      - Bing_Ep3771@outlook.com
      - bingep@qq.com
      - bingep3307@gmail.com;
